### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by Quark195** [jcerezochem/fcc_tools#2] opened 2021-10-07 20:19 UTC
Dear developer!
I would like to use your program, but the following problems occurred during the compilation process.

```
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./fix_time_stamps.sh
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./fix_time_stamps.sh
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./configure --bindir INSTALLPATH 
configure: error: expected an absolute directory name for --bindir: INSTALLPATH
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./configure --bindir: home/quark/fcc_tools-master
configure: error: unrecognized option: `--bindir:'
Try `./configure --help' for more information
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./configure --bindir home/quark/fcc_tools-master 
configure: error: expected an absolute directory name for --bindir: home/quark/fcc_tools-master
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./configure --bindir home/quark/fcc_tools-master
configure: error: expected an absolute directory name for --bindir: home/quark/fcc_tools-master
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ^C
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./configure --bindir=home/quark/fcc_tools-master
configure: error: expected an absolute directory name for --bindir: home/quark/fcc_tools-master
(base) quark@quark-virtual-machine:~/fcc_tools-master$ ./configure --bindir=/home/quark/fcc_tools-master
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gfortran... gfortran
checking whether the Fortran compiler works... yes
checking for Fortran compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking for dsyev in -llapack... yes
forrtl: severe (24): end-of-file during read, unit 5, file /proc/5804/fd/0, line 25, position 0
Image              PC                Routine            Line        Source             
sort               000000000040C80B  Unknown               Unknown  Unknown
sort               0000000000430E9E  Unknown               Unknown  Unknown
sort               000000000040425D  Unknown               Unknown  Unknown
sort               0000000000403822  Unknown               Unknown  Unknown
libc-2.31.so       0000153E9A3ED0B3  __libc_start_main     Unknown  Unknown
sort               000000000040372E  Unknown               Unknown  Unknown
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/generators/Makefile
config.status: creating python/Makefile
config.status: creating tests/Makefile
forrtl: severe (24): end-of-file during read, unit 5, file /proc/5972/fd/0, line 25, position 0
Image              PC                Routine            Line        Source             
sort               000000000040C80B  Unknown               Unknown  Unknown
sort               0000000000430E9E  Unknown               Unknown  Unknown
sort               000000000040425D  Unknown               Unknown  Unknown
sort               0000000000403822  Unknown               Unknown  Unknown
libc-2.31.so       000015055DAFA0B3  __libc_start_main     Unknown  Unknown
sort               000000000040372E  Unknown               Unknown  Unknown
forrtl: severe (24): end-of-file during read, unit 5, file /proc/5977/fd/0, line 77, position 0
Image              PC                Routine            Line        Source             
sort               000000000040C80B  Unknown               Unknown  Unknown
sort               0000000000430E9E  Unknown               Unknown  Unknown
sort               000000000040425D  Unknown               Unknown  Unknown
sort               0000000000403822  Unknown               Unknown  Unknown
libc-2.31.so       000014E3144BC0B3  __libc_start_main     Unknown  Unknown
sort               000000000040372E  Unknown               Unknown  Unknown
(base) quark@quark-virtual-machine:~/fcc_tools-master$ make
Making all in src/generators
make[1]: вход в каталог «/home/quark/fcc_tools-master/src/generators»
gfortran   -c -o version.o version.f90
gfortran   -c -o ../modules/verbosity.o ../modules/verbosity.f90
gfortran   -c -o ../modules/constants.o ../modules/constants.f90
gfortran   -c -o ../modules/alerts.o ../modules/alerts.f90
gfortran   -c -o ../modules/MatrixMod_red.o ../modules/MatrixMod_red.f90
gfortran   -c -o ../modules/line_preprocess.o ../modules/line_preprocess.f90
gfortran   -c -o ../modules/fcc_basics.o ../modules/fcc_basics.f90
gfortran   -c -o ../modules/gamess_manage.o ../modules/gamess_manage.f90
gfortran   -c -o ../modules/gaussian_manage.o ../modules/gaussian_manage.f90
gfortran   -c -o ../modules/cfour_manage.o ../modules/cfour_manage.f90
gfortran   -c -o ../modules/gmx_manage.o ../modules/gmx_manage.f90
gfortran   -c -o ../modules/psi4_manage.o ../modules/psi4_manage.f90
gfortran   -c -o ../modules/molcas_manage.o ../modules/molcas_manage.f90
gfortran   -c -o ../modules/molden_manage.o ../modules/molden_manage.f90
gfortran   -c -o ../modules/molpro_manage.o ../modules/molpro_manage.f90
gfortran   -c -o ../modules/turbomol_manage.o ../modules/turbomol_manage.f90
gfortran   -c -o ../modules/orca_manage.o ../modules/orca_manage.f90
gfortran   -c -o ../modules/fcc_manage.o ../modules/fcc_manage.f90
gfortran   -c -o ../modules/fcc_io.o ../modules/fcc_io.f90
gfortran   -c -o ../modules/vibrational_analysis.o ../modules/vibrational_analysis.f90
gfortran   -c -o gen_fcc_state.o gen_fcc_state.f90
gen_fcc_state.f90:401:74:

  401 |             Freq(i) = dsign(dsqrt(dabs(Freq(i))*HARTtoJ/BOHRtoM**2/AMUtoKG)/2.d0/pi/cvel/1.d2,Freq(i))
      |                                                                          1
Error: Symbol ‘amutokg’ at (1) has no IMPLICIT type; did you mean ‘autokg’?
gen_fcc_state.f90:401:88:

  401 |           Freq(i) = dsign(dsqrt(dabs(Freq(i))*HARTtoJ/BOHRtoM**2/AMUtoKG)/2.d0/pi/cvel/1.d2,Freq(i))
      |                                                                                      1

Error: Symbol ‘cvel’ at (1) has no IMPLICIT type; did you mean ‘vec’?
gen_fcc_state.f90:164:12:

  164 |         j = atnum_from_atmass(Mass(i))
      |            1
Error: Function ‘atnum_from_atmass’ at (1) has no IMPLICIT type; did you mean ‘atnum_from_atname’?
gen_fcc_state.f90:465:20:

  465 |                 k = atnum_from_atmass(Mass(i))
      |                    1
Error: Function ‘atnum_from_atmass’ at (1) has no IMPLICIT type; did you mean ‘atnum_from_atname’?
make[1]: *** [Makefile:461: gen_fcc_state.o] Ошибка 1
make[1]: выход из каталога «/home/quark/fcc_tools-master/src/generators»
make: *** [Makefile:327: all-recursive] Ошибка 1
(base) quark@quark-virtual-machine:~/fcc_tools-master$ 

```

Please help me fix it.
Best regards, Eugene

**Comment by jcerezochem** [comment] 2021-10-07 21:23
Dear Eugene,

Thanks for contacting me. The last commit added new variables that broke the code, and it should be fixed in the latest commit I've just added. Please, let me know if it now works correctly. 

If you are using FCclasses, you may find useful the new version of the code (which includes an updated version of fcc_tools) that we are about to release. I can let you know when the release is ready if you are interested.

Regards,

Javier

**Comment by Quark195** [comment] 2021-10-08 18:55
Dear Javier,
Thank you for fixing the bug so quickly. The program was installed and I almost figured out the interface. I would be grateful if you notify me about the release of a new version. The program is really powerful and useful for doing scientific research. However, I cannot figure out with what keys I can generate files for states 1 and 2 from the Orca output files.
Command
/ home / quark / fcc_tools-master / gen_fcc_state -i IrAmbt_PBE0_SVP_OPT_IR.hess -ft orca4 allows me to generate a file with geometry and hessian, but I cannot copy the normal modes and frequencies for the FCclasses program.  I also noticed the program for some reason skips the C and S atoms. NOTE: Element cannot be set from mass   12.0110. AtNum set to 0, name set to X.  

Perhaps I am doing something wrong.
Please help me figure it out

Best regards, Eugene

[IrAmbiME2_PBE0_SVP_IR.txt](https://github.com/jcerezochem/fcc_tools/files/7313545/IrAmbiME2_PBE0_SVP_IR.txt)
[IrAmbiME2_PBE0_SVP_IR_hess.txt](https://github.com/jcerezochem/fcc_tools/files/7313546/IrAmbiME2_PBE0_SVP_IR_hess.txt)

**Comment by jcerezochem** [comment] 2022-02-24 17:49
Dear Eugene,

My apologies for the too long delay. I had some problems following the issue timely, and I did not realize your reply until today.

First, regarding normal modes and frequencies, notice that they are not included within the new state files (.fcc) since the latest version of the code [FCclasses3](http://www.pi.iccom.cnr.it/fcclasses) handles this. You can still generate old state files with the flag `-write-fcc2`, which contain normal mode matrices and frequencies. Additional information about normal modes can be obtained with the flag `-write-modes`.

Regarding the error about the masses, it is a bit messy to get atom names from masses. In any case, this could be better handled by searching for the closest mass with no threshold. I will try to fix this soon, but I was able to run your example with no warning for now. Could you please report the file that leads to errors? 

Thanks!

**Comment by Quark195** [comment] 2022-02-24 22:58
Dear Javier,
Thank you very much for not forgetting about my problem. I'll check it out soon and let you know
Best regards, Eugene

**Comment by jcerezochem** [comment] 2022-07-29 08:55
I will assume that the problem is solved. Note that the structure of the tools has been changed, and they are now included in the [FCclasses3](http://www.iccom.cnr.it/en/fcclasses/) package.

**Closed as completed by jcerezochem** 2022-07-29 08:55 UTC
